name: Gerar APK Flutter
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Gerar estrutura nativa se necessario
        run: |
          if [ ! -d "android" ]; then
            cp pubspec.yaml pubspec.backup.yaml
            flutter create --org com.lfl .
            cp pubspec.backup.yaml pubspec.yaml
            rm -f pubspec.backup.yaml
          fi

      - name: Instalar dependencias
        run: flutter pub get

      - name: Atualizar Icone do Aplicativo
        run: flutter pub run flutter_launcher_icons || true

      - name: Gerar chave de assinatura oficial LFL
        run: |
          keytool -genkeypair -v \
            -keystore android/app/lfl_key.jks \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias lflkey \
            -storepass senhaSeguraLfl2026 \
            -keypass senhaSeguraLfl2026 \
            -dname "CN=Lysandro Luiz, OU=Suporte, O=LFL Informatica, L=Curitiba, ST=PR, C=BR"

      - name: Compilar APK
        run: flutter build apk --release

      - name: Assinar APK com certificado oficial
        run: |
          $ANDROID_HOME/build-tools/34.0.0/apksigner sign \
            --ks android/app/lfl_key.jks \
            --ks-pass pass:senhaSeguraLfl2026 \
            --ks-key-alias lflkey \
            --key-pass pass:senhaSeguraLfl2026 \
            --out build/app/outputs/flutter-apk/App-LFL-Informatica.apk \
            build/app/outputs/flutter-apk/app-release.apk

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: App-LFL-Informatica
          path: build/app/outputs/flutter-apk/App-LFL-Informatica.apk
